export const QUERY_KEYS = {
  USE_MINT: "USE_MINT",
  USE_GET_POOLS: "USE_GET_POOLS",
  USE_GET_POSITION: "USE_GET_POSITION",
  USE_GET_POSITIONS: "USE_GET_POSITIONS",
  USE_POSITIONS: "USE_POSITIONS",
};
