_default:
  @just --list

# copy .env.example to .env.local
cp-env:
  cp .env.example .env.local

lint:
  npm run lint
alias l := lint

test:
  npm run test
alias t := test

run:
  npm run dev
alias r := run

build:
  npm run build
alias b := build

# generate codebase.md that is useful to feed to LLMs
ai-digest:
   npx ai-digest -i app --show-output-files
