_default:
  @just --list

# setup wallets for synpress. must run this when caches do not exist.
setup-wallets:
  # NOTE - the path is relative to playwright.config.ts
  npx synpress -d ./e2e-tests/wallet-setup

install-browsers:
  npx playwright install

# flame-defi e2e tests
# Usage: just run-e2e-tests [ui]
run-e2e-tests *args="":
  # NOTE - the path is relative to playwright.config.ts
  npx playwright test ./e2e-tests {{ if args == "ui" { "--ui" } else { "" } }}
